import {
  IsString,
  IsEmail,
  IsEnum,
  IsOptional,
  MaxLength,
  Matches,
  IsArray,
  ArrayNotEmpty,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { userRole } from '../enums/userRole.enum';
import { ChallengeLevel } from '../enums/challengeLevel.enum';
import { ChallengeType } from '../enums/challengeType.enum';
import { ReferralSource } from '../enums/referralSource.enum';
import { AgeGroup } from '../enums/ageGroup.enum';
import { AuthProvider } from '../../auth/enum/authProvider.enum';

export class CreateUserDto {
  /**
   * Email field
   */
  @ApiProperty({
    type: 'string',
    example: 'fatimaaminu@mail.com',
  })
  @IsEmail()
  @IsOptional()
  @MaxLength(150)
  email?: string;

  @ApiProperty({
    type: 'string',
    example: 'fatimaaminu@mail.com',
  })
  @IsString()
  @IsOptional()
  @MaxLength(150)
  username?: string;

  @ApiProperty({
    type: 'string',
    example: 'Fatima Aminu',
    description: 'Full name of the user',
  })
  @IsString()
  @IsOptional()
  @MaxLength(150)
  fullname?: string;

  /**
   * Password should contain numbers, alphabets, and uppercase
   */
  @ApiProperty({
    type: 'string',
    example: '@Password123',
    description:
      'Password must include at least one uppercase letter, one lowercase letter, one number, and one special character.',
  })
  @IsString()
  @IsOptional()
  @MaxLength(225)
  @Matches(
    /^(?=.*[!@#$%^&])(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9!@#$%^&*]{8,16}$/,
    {
      message:
        'Password must include at least one uppercase letter, one lowercase letter, one number, and one special character.',
    },
  )
  password?: string;

  /**
   * User role
   */
  @ApiProperty({
    enum: userRole,
    example: userRole.USER,
  })
  @IsEnum(userRole)
  @IsOptional()
  @Transform(
    ({ value }: { value: userRole | undefined }) => value ?? userRole.USER,
  )
  userRole?: userRole;

  /**
   * Wallet address (required for wallet signup)
   */
  @ApiProperty({
    example: '0x1234567890abcdef...',
    required: false,
  })
  @IsString()
  @IsOptional()
  walletAddress?: string;

  /**
   * Public key (required for wallet signup)
   */
  @ApiProperty({
    example: '0xabcdef123456...',
    required: false,
  })
  @IsString()
  @IsOptional()
  publicKey?: string;

  /**
   * Auth provider (local, google, wallet)
   */
  @ApiProperty({
    enum: AuthProvider,
    example: AuthProvider.LOCAL,
    required: false,
  })
  @IsEnum(AuthProvider)
  @IsOptional()
  provider?: string;
  /**
   * Autogenerated from Google when signing up with Googlee
   */
  @ApiProperty({
    type: 'string',
    example: 'poiuytrdspoiuytrewaxcvbnmml;poiuytrdsdcvbnm]',
  })
  @IsString()
  @IsOptional()
  @MaxLength(225)
  googleId?: string;

  @ApiProperty({
    enum: ChallengeLevel,
    example: ChallengeLevel.INTERMEDIATE,
  })
  @IsOptional()
  @IsEnum(ChallengeLevel)
  challengeLevel?: ChallengeLevel;

  @ApiProperty({
    enum: ChallengeType,
    isArray: true,
    example: [ChallengeType.CODING, ChallengeType.LOGIC],
  })
  @IsOptional()
  @IsArray()
  @ArrayNotEmpty()
  @IsEnum(ChallengeType, { each: true })
  challengeTypes?: ChallengeType[];

  @ApiProperty({
    enum: ReferralSource,
    example: ReferralSource.GOOGLE,
    required: false,
  })
  @IsOptional()
  @IsEnum(ReferralSource)
  referralSource?: ReferralSource;

  @ApiProperty({
    enum: AgeGroup,
    example: AgeGroup.YOUNG_ADULT,
  })
  @IsOptional()
  @IsEnum(AgeGroup)
  ageGroup?: AgeGroup;

  /**
   * Country of the user
   */
  @ApiProperty({
    example: 'United States',
    required: false,
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  country?: string;

  /**
   * User interests
   */
  @ApiProperty({
    example: ['Coding', 'Design'],
    required: false,
    type: [String],
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  interests?: string[];

  /**
   * User occupation
   */
  @ApiProperty({
    example: 'Software Engineer',
    required: false,
  })
  @IsOptional()
  @IsString()
  @MaxLength(150)
  occupation?: string;

  /**
   * User goals
   */
  @ApiProperty({
    example: ['Learn NestJS', 'Build an app'],
    required: false,
    type: [String],
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  goals?: string[];

  /**
   * Available hours for learning
   */
  @ApiProperty({
    example: ['09:00', '10:00'],
    required: false,
    type: [String],
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  availableHours?: string[];

  /**
   * User bio
   */
  @ApiProperty({
    example: 'I am a passionate developer...',
    required: false,
  })
  @IsOptional()
  @IsString()
  bio?: string;
}